name: Build
on:
  push:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t richodemus/sentyalie .
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Push to GCR
        run: gcloud info

#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: richodemus/sentyalie
#          tag_with_ref: true

